// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: libmihomo/proto/command/command.proto

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 → server default (1 s). Clamped to [100ms, 10s].
	IntervalMs    int64 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StatusMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes/sec for the current second.
	Up   int64 `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	Down int64 `protobuf:"varint,2,opt,name=down,proto3" json:"down,omitempty"`
	// Cumulative since the extension started.
	UpTotal   int64 `protobuf:"varint,3,opt,name=up_total,json=upTotal,proto3" json:"up_total,omitempty"`
	DownTotal int64 `protobuf:"varint,4,opt,name=down_total,json=downTotal,proto3" json:"down_total,omitempty"`
	// Currently tracked connections.
	Connections int64 `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	// Extension process phys_footprint (bytes) — same number jetsam compares.
	MemoryResident int64 `protobuf:"varint,6,opt,name=memory_resident,json=memoryResident,proto3" json:"memory_resident,omitempty"`
	// Per-process budget set at Start (resident + os_proc_available_memory).
	MemoryBudget  int64 `protobuf:"varint,7,opt,name=memory_budget,json=memoryBudget,proto3" json:"memory_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *StatusMessage) GetUp() int64 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *StatusMessage) GetDown() int64 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *StatusMessage) GetUpTotal() int64 {
	if x != nil {
		return x.UpTotal
	}
	return 0
}

func (x *StatusMessage) GetDownTotal() int64 {
	if x != nil {
		return x.DownTotal
	}
	return 0
}

func (x *StatusMessage) GetConnections() int64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *StatusMessage) GetMemoryResident() int64 {
	if x != nil {
		return x.MemoryResident
	}
	return 0
}

func (x *StatusMessage) GetMemoryBudget() int64 {
	if x != nil {
		return x.MemoryBudget
	}
	return 0
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{2}
}

type LogMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mihomo log level: 0=DEBUG 1=INFO 2=WARNING 3=ERROR. SILENT (=4) is
	// a host-side display filter and never appears on the wire.
	Level   int32  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Unix nanoseconds captured the moment mihomo emitted the event.
	// The host uses this directly so the timestamp shown in the live UI
	// matches the one written to the on-disk session log, even when the
	// gRPC frame is delayed by a backpressure cycle.
	TimestampNs   int64 `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *LogMessage) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LogMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *LogMessage) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{4}
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{5}
}

type ControllerRequestRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Absolute path plus optional query string, e.g. "/proxies" or
	// "/group/JP%2FTokyo/delay?timeout=5000". The caller is responsible
	// for percent-encoding path segments.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerRequestRequest) Reset() {
	*x = ControllerRequestRequest{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerRequestRequest) ProtoMessage() {}

func (x *ControllerRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerRequestRequest.ProtoReflect.Descriptor instead.
func (*ControllerRequestRequest) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *ControllerRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ControllerRequestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ControllerRequestRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ControllerRequestRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ControllerRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerRequestResponse) Reset() {
	*x = ControllerRequestResponse{}
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerRequestResponse) ProtoMessage() {}

func (x *ControllerRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libmihomo_proto_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerRequestResponse.ProtoReflect.Descriptor instead.
func (*ControllerRequestResponse) Descriptor() ([]byte, []int) {
	return file_libmihomo_proto_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *ControllerRequestResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ControllerRequestResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_libmihomo_proto_command_command_proto protoreflect.FileDescriptor

const file_libmihomo_proto_command_command_proto_rawDesc = "" +
	"\n" +
	"%libmihomo/proto/command/command.proto\x12\x10proxycat.command\"0\n" +
	"\rStatusRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x03R\n" +
	"intervalMs\"\xdd\x01\n" +
	"\rStatusMessage\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\x03R\x02up\x12\x12\n" +
	"\x04down\x18\x02 \x01(\x03R\x04down\x12\x19\n" +
	"\bup_total\x18\x03 \x01(\x03R\aupTotal\x12\x1d\n" +
	"\n" +
	"down_total\x18\x04 \x01(\x03R\tdownTotal\x12 \n" +
	"\vconnections\x18\x05 \x01(\x03R\vconnections\x12'\n" +
	"\x0fmemory_resident\x18\x06 \x01(\x03R\x0ememoryResident\x12#\n" +
	"\rmemory_budget\x18\a \x01(\x03R\fmemoryBudget\"\f\n" +
	"\n" +
	"LogRequest\"_\n" +
	"\n" +
	"LogMessage\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\"\x0f\n" +
	"\rReloadRequest\"\x10\n" +
	"\x0eReloadResponse\"}\n" +
	"\x18ControllerRequestRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"G\n" +
	"\x19ControllerRequestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body2\xea\x02\n" +
	"\aCommand\x12U\n" +
	"\x0fSubscribeStatus\x12\x1f.proxycat.command.StatusRequest\x1a\x1f.proxycat.command.StatusMessage0\x01\x12M\n" +
	"\rSubscribeLogs\x12\x1c.proxycat.command.LogRequest\x1a\x1c.proxycat.command.LogMessage0\x01\x12K\n" +
	"\x06Reload\x12\x1f.proxycat.command.ReloadRequest\x1a .proxycat.command.ReloadResponse\x12l\n" +
	"\x11ControllerRequest\x12*.proxycat.command.ControllerRequestRequest\x1a+.proxycat.command.ControllerRequestResponseB5Z3github.com/proxycat/libmihomo/proto/command;commandb\x06proto3"

var (
	file_libmihomo_proto_command_command_proto_rawDescOnce sync.Once
	file_libmihomo_proto_command_command_proto_rawDescData []byte
)

func file_libmihomo_proto_command_command_proto_rawDescGZIP() []byte {
	file_libmihomo_proto_command_command_proto_rawDescOnce.Do(func() {
		file_libmihomo_proto_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libmihomo_proto_command_command_proto_rawDesc), len(file_libmihomo_proto_command_command_proto_rawDesc)))
	})
	return file_libmihomo_proto_command_command_proto_rawDescData
}

var file_libmihomo_proto_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_libmihomo_proto_command_command_proto_goTypes = []any{
	(*StatusRequest)(nil),             // 0: proxycat.command.StatusRequest
	(*StatusMessage)(nil),             // 1: proxycat.command.StatusMessage
	(*LogRequest)(nil),                // 2: proxycat.command.LogRequest
	(*LogMessage)(nil),                // 3: proxycat.command.LogMessage
	(*ReloadRequest)(nil),             // 4: proxycat.command.ReloadRequest
	(*ReloadResponse)(nil),            // 5: proxycat.command.ReloadResponse
	(*ControllerRequestRequest)(nil),  // 6: proxycat.command.ControllerRequestRequest
	(*ControllerRequestResponse)(nil), // 7: proxycat.command.ControllerRequestResponse
}
var file_libmihomo_proto_command_command_proto_depIdxs = []int32{
	0, // 0: proxycat.command.Command.SubscribeStatus:input_type -> proxycat.command.StatusRequest
	2, // 1: proxycat.command.Command.SubscribeLogs:input_type -> proxycat.command.LogRequest
	4, // 2: proxycat.command.Command.Reload:input_type -> proxycat.command.ReloadRequest
	6, // 3: proxycat.command.Command.ControllerRequest:input_type -> proxycat.command.ControllerRequestRequest
	1, // 4: proxycat.command.Command.SubscribeStatus:output_type -> proxycat.command.StatusMessage
	3, // 5: proxycat.command.Command.SubscribeLogs:output_type -> proxycat.command.LogMessage
	5, // 6: proxycat.command.Command.Reload:output_type -> proxycat.command.ReloadResponse
	7, // 7: proxycat.command.Command.ControllerRequest:output_type -> proxycat.command.ControllerRequestResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libmihomo_proto_command_command_proto_init() }
func file_libmihomo_proto_command_command_proto_init() {
	if File_libmihomo_proto_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libmihomo_proto_command_command_proto_rawDesc), len(file_libmihomo_proto_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libmihomo_proto_command_command_proto_goTypes,
		DependencyIndexes: file_libmihomo_proto_command_command_proto_depIdxs,
		MessageInfos:      file_libmihomo_proto_command_command_proto_msgTypes,
	}.Build()
	File_libmihomo_proto_command_command_proto = out.File
	file_libmihomo_proto_command_command_proto_goTypes = nil
	file_libmihomo_proto_command_command_proto_depIdxs = nil
}
