// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Command_SubscribeStatus_FullMethodName = "/proxycat.command.Command/SubscribeStatus"
	Command_SubscribeLogs_FullMethodName   = "/proxycat.command.Command/SubscribeLogs"
)

// CommandClient is the client API for Command service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Command service exposes streaming subscriptions used by the iOS host
// app. Mirrors the shape of sing-box's daemon.StartedService (gRPC over
// Unix domain socket inside the App Group container) but trimmed to the
// fields ProxyCat actually needs. Mihomo's REST controller is
// intentionally NOT used here — that surface is for the end-user.
type CommandClient interface {
	// Streams a Status message every IntervalMs (default 1000).
	SubscribeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusMessage], error)
	// Streams every log event produced by mihomo from subscription onward.
	SubscribeLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error)
}

type commandClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandClient(cc grpc.ClientConnInterface) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) SubscribeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[0], Command_SubscribeStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeStatusClient = grpc.ServerStreamingClient[StatusMessage]

func (c *commandClient) SubscribeLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[1], Command_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeLogsClient = grpc.ServerStreamingClient[LogMessage]

// CommandServer is the server API for Command service.
// All implementations must embed UnimplementedCommandServer
// for forward compatibility.
//
// Command service exposes streaming subscriptions used by the iOS host
// app. Mirrors the shape of sing-box's daemon.StartedService (gRPC over
// Unix domain socket inside the App Group container) but trimmed to the
// fields ProxyCat actually needs. Mihomo's REST controller is
// intentionally NOT used here — that surface is for the end-user.
type CommandServer interface {
	// Streams a Status message every IntervalMs (default 1000).
	SubscribeStatus(*StatusRequest, grpc.ServerStreamingServer[StatusMessage]) error
	// Streams every log event produced by mihomo from subscription onward.
	SubscribeLogs(*LogRequest, grpc.ServerStreamingServer[LogMessage]) error
	mustEmbedUnimplementedCommandServer()
}

// UnimplementedCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServer struct{}

func (UnimplementedCommandServer) SubscribeStatus(*StatusRequest, grpc.ServerStreamingServer[StatusMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeStatus not implemented")
}
func (UnimplementedCommandServer) SubscribeLogs(*LogRequest, grpc.ServerStreamingServer[LogMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedCommandServer) mustEmbedUnimplementedCommandServer() {}
func (UnimplementedCommandServer) testEmbeddedByValue()                 {}

// UnsafeCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServer will
// result in compilation errors.
type UnsafeCommandServer interface {
	mustEmbedUnimplementedCommandServer()
}

func RegisterCommandServer(s grpc.ServiceRegistrar, srv CommandServer) {
	// If the following call panics, it indicates UnimplementedCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Command_ServiceDesc, srv)
}

func _Command_SubscribeStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServer).SubscribeStatus(m, &grpc.GenericServerStream[StatusRequest, StatusMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeStatusServer = grpc.ServerStreamingServer[StatusMessage]

func _Command_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServer).SubscribeLogs(m, &grpc.GenericServerStream[LogRequest, LogMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeLogsServer = grpc.ServerStreamingServer[LogMessage]

// Command_ServiceDesc is the grpc.ServiceDesc for Command service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Command_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxycat.command.Command",
	HandlerType: (*CommandServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeStatus",
			Handler:       _Command_SubscribeStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _Command_SubscribeLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/command/command.proto",
}
