// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: libmihomo/proto/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Command_SubscribeStatus_FullMethodName   = "/proxycat.command.Command/SubscribeStatus"
	Command_SubscribeLogs_FullMethodName     = "/proxycat.command.Command/SubscribeLogs"
	Command_Reload_FullMethodName            = "/proxycat.command.Command/Reload"
	Command_SetLogLevel_FullMethodName       = "/proxycat.command.Command/SetLogLevel"
	Command_ControllerRequest_FullMethodName = "/proxycat.command.Command/ControllerRequest"
)

// CommandClient is the client API for Command service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Command service exposes streaming subscriptions and unary command RPCs
// used by the iOS host app. Mirrors the shape of sing-box's
// daemon.StartedService (gRPC over Unix domain socket inside the App
// Group container) but trimmed to the fields ProxyCat actually needs.
// Host-facing control traffic stays on this gRPC channel; when the
// native UI needs mihomo's REST handlers, the extension proxies the
// request internally to mihomo's private Unix-domain controller socket.
type CommandClient interface {
	// Streams a Status message every IntervalMs (default 1000).
	SubscribeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusMessage], error)
	// Streams every log event produced by mihomo from subscription onward.
	SubscribeLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error)
	// Asks the running mihomo core to re-read runtime_settings.json + the
	// active profile YAML, then hot-apply via hub.ApplyConfig. Used by the
	// host whenever the user changes the active profile, edits the active
	// YAML, or toggles a runtime setting that requires a full rebuild
	// (e.g. external controller). Errors (mihomo not started, YAML parse
	// failure, semantic config rejection) flow back via gRPC status.
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	// Legacy diagnostic hook for changing mihomo's own logrus print level.
	// The current host app does not use this for the Logs-view picker; live
	// and saved logs are captured unfiltered and Swift filters locally.
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
	// Proxies a single native-controller HTTP request through the command
	// IPC channel. The extension side executes the request with Go's
	// net/http client over mihomo's private Unix-domain controller socket.
	// This keeps host ↔ extension IPC on one gRPC transport while still
	// reusing mihomo's existing REST handlers for /proxies, /connections,
	// /group/.../delay, etc.
	ControllerRequest(ctx context.Context, in *ControllerRequestRequest, opts ...grpc.CallOption) (*ControllerRequestResponse, error)
}

type commandClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandClient(cc grpc.ClientConnInterface) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) SubscribeStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[0], Command_SubscribeStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeStatusClient = grpc.ServerStreamingClient[StatusMessage]

func (c *commandClient) SubscribeLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[1], Command_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeLogsClient = grpc.ServerStreamingClient[LogMessage]

func (c *commandClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, Command_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLogLevelResponse)
	err := c.cc.Invoke(ctx, Command_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) ControllerRequest(ctx context.Context, in *ControllerRequestRequest, opts ...grpc.CallOption) (*ControllerRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControllerRequestResponse)
	err := c.cc.Invoke(ctx, Command_ControllerRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServer is the server API for Command service.
// All implementations must embed UnimplementedCommandServer
// for forward compatibility.
//
// Command service exposes streaming subscriptions and unary command RPCs
// used by the iOS host app. Mirrors the shape of sing-box's
// daemon.StartedService (gRPC over Unix domain socket inside the App
// Group container) but trimmed to the fields ProxyCat actually needs.
// Host-facing control traffic stays on this gRPC channel; when the
// native UI needs mihomo's REST handlers, the extension proxies the
// request internally to mihomo's private Unix-domain controller socket.
type CommandServer interface {
	// Streams a Status message every IntervalMs (default 1000).
	SubscribeStatus(*StatusRequest, grpc.ServerStreamingServer[StatusMessage]) error
	// Streams every log event produced by mihomo from subscription onward.
	SubscribeLogs(*LogRequest, grpc.ServerStreamingServer[LogMessage]) error
	// Asks the running mihomo core to re-read runtime_settings.json + the
	// active profile YAML, then hot-apply via hub.ApplyConfig. Used by the
	// host whenever the user changes the active profile, edits the active
	// YAML, or toggles a runtime setting that requires a full rebuild
	// (e.g. external controller). Errors (mihomo not started, YAML parse
	// failure, semantic config rejection) flow back via gRPC status.
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	// Legacy diagnostic hook for changing mihomo's own logrus print level.
	// The current host app does not use this for the Logs-view picker; live
	// and saved logs are captured unfiltered and Swift filters locally.
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	// Proxies a single native-controller HTTP request through the command
	// IPC channel. The extension side executes the request with Go's
	// net/http client over mihomo's private Unix-domain controller socket.
	// This keeps host ↔ extension IPC on one gRPC transport while still
	// reusing mihomo's existing REST handlers for /proxies, /connections,
	// /group/.../delay, etc.
	ControllerRequest(context.Context, *ControllerRequestRequest) (*ControllerRequestResponse, error)
	mustEmbedUnimplementedCommandServer()
}

// UnimplementedCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServer struct{}

func (UnimplementedCommandServer) SubscribeStatus(*StatusRequest, grpc.ServerStreamingServer[StatusMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeStatus not implemented")
}
func (UnimplementedCommandServer) SubscribeLogs(*LogRequest, grpc.ServerStreamingServer[LogMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedCommandServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedCommandServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedCommandServer) ControllerRequest(context.Context, *ControllerRequestRequest) (*ControllerRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ControllerRequest not implemented")
}
func (UnimplementedCommandServer) mustEmbedUnimplementedCommandServer() {}
func (UnimplementedCommandServer) testEmbeddedByValue()                 {}

// UnsafeCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServer will
// result in compilation errors.
type UnsafeCommandServer interface {
	mustEmbedUnimplementedCommandServer()
}

func RegisterCommandServer(s grpc.ServiceRegistrar, srv CommandServer) {
	// If the following call panics, it indicates UnimplementedCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Command_ServiceDesc, srv)
}

func _Command_SubscribeStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServer).SubscribeStatus(m, &grpc.GenericServerStream[StatusRequest, StatusMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeStatusServer = grpc.ServerStreamingServer[StatusMessage]

func _Command_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServer).SubscribeLogs(m, &grpc.GenericServerStream[LogRequest, LogMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_SubscribeLogsServer = grpc.ServerStreamingServer[LogMessage]

func _Command_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Command_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Command_ControllerRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).ControllerRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_ControllerRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).ControllerRequest(ctx, req.(*ControllerRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Command_ServiceDesc is the grpc.ServiceDesc for Command service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Command_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxycat.command.Command",
	HandlerType: (*CommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reload",
			Handler:    _Command_Reload_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _Command_SetLogLevel_Handler,
		},
		{
			MethodName: "ControllerRequest",
			Handler:    _Command_ControllerRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeStatus",
			Handler:       _Command_SubscribeStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _Command_SubscribeLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "libmihomo/proto/command/command.proto",
}
